###################################
# Grus 配置文件
###################################

# 插件语言, 默认为zh-CN
# 可用选项请查看 ./Grus/language/ 文件夹
language: zh-CN

# 修仙者境界设定
# 以下默认设定来源于 https://baike.baidu.com/item/凡人修仙传
boundary-settings:
  no-boundary-display: "&f凡人"
  # 等级:应当要有的灵气值
  # 填写时请务必按照 从小到大的顺序填写
  level:
    炼气: 500
    筑基初阶: 1500
    筑基中阶: 7000
    筑基巅峰: 15000
    结丹: 50000
    元婴: 500000
    化神: 5000000
    炼虚: 50000000
    合体: 500000000
    大乘: 5000000000
  # 设置每个等级的显示名
  display:
    炼气: "&f炼气"
    筑基初阶: "&2筑基初阶"
    筑基中阶: "&3筑基中阶"
    筑基巅峰: "&5筑基中阶"
    结丹: "&6炼气"
    元婴: "&d炼气"
    化神: "&s炼气"
    炼虚: "&1炼气"
    合体: "&c合体"
    大乘: "&4大乘"

# 灵根设定
# 灵根指修仙者的属性, 表示修仙者的修行素质
#   伪灵根：具有四、五种属性的灵根，很杂且不充裕，每种属性的灵根都不完全，修炼速度很慢。
#   真灵根：具有两、三种属性的灵根，每种属性灵根充裕。修炼速度较快。
#   天灵根：只有一种属性的单一灵根，灵根充裕。修炼速度是普通灵根的数倍，结丹时没有瓶颈。
lingem-settings:
  # 获得每一种属性的概率
  # 若插件随机到修仙者无法获得任何灵根, 则会获得天灵根且随机一种灵根 (从某种意义上说也算是特别幸运)
  chances:
    金: 0.2
    木: 0.2
    水: 0.2
    火: 0.2
    土: 0.2
  display:
    金: "&6金灵根"
    木: "&2木灵根"
    水: "&9水灵根"
    火: "&c火灵根"
    土: "&e土灵根"

# 境界修为值掉落设定
boundary-exp-drop-settings:
  # 境界经验值怪物掉落模式
  # 可用选项: vanilla/orb/none
  # vanilla: 原版掉落模式, 适用于无其他RPG元素的生存服务器(当然 生存+RPG 也可以 只需要 MythicMobs 调用指令即可 但数值需要进行更改)
  # orb: 真气实体掉落方式, 适用于增加修仙的真实与趣味性, 在 vanilla的基础上 改为 击杀怪物掉落真气实体
  #   但是要注意的是 orb 会改变游戏世界设定将经验堆叠关闭以防止真气球和原版经验球合并
  #   需要您手动将 spigot.yml 当中的 world-settings.default.merge-radius.exp 修改为 -1 才可使用
  # none: 无掉落模式, 适用于安装有自定义实体的插件的自定义RPG实体服务器
  mode: "vanilla"
  # 在真气实体掉落方式下, 真气球的显示名
  chi-orb-name: "&e真气"
  # 以下数值只能为整数, 默认数值则是利用原版怪物的血量进行编写
  monster:
    blaze: 10
    cave-spider: 6
    creeper: 10
    elder-guardian: 40
    enderman: 20
    endermite: 4
    evoker: 12
    giant: 50
    guardian: 15
    husk: 10
    illager: 12
    illusioner: 16
    pig-zombie: 10
    silverfish: 4
    skeleton: 10
    spell-caster: 10
    spider: 8
    stray: 10
    vex: 7
    vindicator: 12
    witch: 13
    wither: 150
    wither-skeleton: 10
    zombie: 10
    zombie-villager: 10

attribute-settings:
  attributes:
    气血: 20
    灵气: 20
    物理攻击: 1
    物理防御: 0