###################################
# Grus 配置文件
###################################

# 插件语言, 默认为zh-CN
# 可用选项请查看 ./Grus/language/ 文件夹
language: zh-CN

# 修仙者境界设定
# 以下默认设定来源于 https://baike.baidu.com/item/凡人修仙传
boundary-settings:
  no-boundary-display: "&f凡人"
  # 等级:应当要有的灵气值
  # 填写时请务必按照 从小到大的顺序填写
  level:
    炼气: 500
    筑基初阶: 1500
    筑基中阶: 7000
    筑基巅峰: 15000
    结丹: 50000
    元婴: 500000
    化神: 5000000
    炼虚: 50000000
    合体: 500000000
    大乘: 5000000000
  # 设置每个等级的显示颜色
  color-code:
    炼气: "&f炼气"
    筑基初阶: "&2筑基初阶"
    筑基中阶: "&3筑基中阶"
    筑基巅峰: "&5筑基中阶"
    结丹: "&6炼气"
    元婴: "&d炼气"
    化神: "&s炼气"
    炼虚: "&1炼气"
    合体: "&c合体"
    大乘: "&4大乘"

# 灵根设定
# 灵根指修仙者的属性, 表示修仙者的修行素质
#   伪灵根：具有四、五种属性的灵根，很杂且不充裕，每种属性的灵根都不完全，修炼速度很慢。
#   真灵根：具有两、三种属性的灵根，每种属性灵根充裕。修炼速度较快。
#   天灵根：只有一种属性的单一灵根，灵根充裕。修炼速度是普通灵根的数倍，结丹时没有瓶颈。
lingem-settings:
  # 获得每一种属性的概率
  # 若插件随机到修仙者无法获得任何灵根, 则会获得天灵根且随机一种灵根 (从某种意义上说也算是特别幸运)
  chances:
    金: 0.2
    木: 0.2
    水: 0.2
    火: 0.2
    土: 0.2